CREATE  TABLE `agenda`.`AGENDA` (

  `ID` BIGINT NOT NULL AUTO_INCREMENT ,

  `EVENT_NAME` VARCHAR(45) NOT NULL ,

  `EVENT_DETAIL` VARCHAR(200) NULL ,

  `EVENT_START_DATE` DATE NOT NULL ,

  `EVENT_START_TIME` TIME NOT NULL ,

  `EVENT_END_DATE` DATE NOT NULL ,

  `EVENT_END_TIME` TIME NOT NULL ,

  `EVENT_PLACE` VARCHAR(45) NULL ,

  PRIMARY KEY (`ID`) );

